In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/customer_shopping_behavior.xlsx")

In [ ]:
df.head()

  Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases
0  1\t55\tMale\tBlouse\tClothing\t53\tKentucky\tL...
1  2\t19\tMale\tSweater\tClothing\t64\tMaine\tL\t...
2  3\t50\tMale\tJeans\tClothing\t73\tMassachusett...
3  4\t21\tMale\tSandals\tFootwear\t90\tRhode Isla...
4  5\t45\tMale\tBlouse\tClothing\t49\tOregon\tM\t...

In [ ]:
df.tail()

     Customer ID\tAge\tGender\tItem Purchased\tCategory\tPurchase Amount (USD)\tLocation\tSize\tColor\tSeason\tReview Rating\tSubscription Status\tShipping Type\tDiscount Applied\tPromo Code Used\tPrevious Purchases\tPayment Method\tFrequency of Purchases
3895  3896\t40\tFemale\tHoodie\tClothing\t28\tVirgin...
3896  3897\t52\tFemale\tBackpack\tAccessories\t49\tI...
3897  3898\t46\tFemale\tBelt\tAccessories\t33\tNew J...
3898  3899\t44\tFemale\tShoes\tFootwear\t77\tMinneso...
3899  3900\t52\tFemale\tHandbag\tAccessories\t81\tCa...

In [ ]:
len(df)

3900

In [ ]:
df.shape

(3900, 1)

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [ ]:
len(df)

3900

In [ ]:
df.shape

(3900, 18)

In [ ]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

**  Data Cleaning**

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df['Item Purchased']

0         Blouse
1        Sweater
2          Jeans
3        Sandals
4         Blouse
          ...
3895      Hoodie
3896    Backpack
3897        Belt
3898       Shoes
3899     Handbag
Name: Item Purchased, Length: 3900, dtype: object

In [ ]:
df['Item Purchased'].unique()

array(['Blouse', 'Sweater', 'Jeans', 'Sandals', 'Sneakers', 'Shirt',
       'Shorts', 'Coat', 'Handbag', 'Shoes', 'Dress', 'Skirt',
       'Sunglasses', 'Pants', 'Jacket', 'Hoodie', 'Jewelry', 'T-shirt',
       'Scarf', 'Hat', 'Socks', 'Backpack', 'Belt', 'Boots', 'Gloves'],
      dtype=object)

In [ ]:
df['Category'].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [ ]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories    [Handbag, Sunglasses, Jewelry, Scarf, Hat, Bac...
Clothing       [Blouse, Sweater, Jeans, Shirt, Shorts, Dress,...
Footwear                       [Sandals, Sneakers, Shoes, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [ ]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessory    [Handbag, Sunglasses, Scarf, Belt]
Cloth            [Jeans, Shorts, Dress, Hoodie]
Footwear             [Sandals, Sneakers, Boots]
Name: Item Purchased, dtype: object

In [ ]:
correct_mapping = {
  "Blouse": "Clothing",
  "Sweater": "Clothing",
  "Jeans": "Clothing",
  "Dress": "Clothing",
  "Shorts": "Clothing",
  "Shirt": "Clothing",
  "Coat": "Outerwear",
  "Pants": "Clothing",
  "T-shirt": "Clothing",
  "Skirt": "Clothing",
  "Hoodie": "Clothing",
  "Socks": "Clothing",

  "Handbag": "Accessories",
  "Sunglasses": "Accessories",
  "Jewelry": "Accessories",
  "Scarf": "Accessories",
  "Hat": "Accessories",
  "Belt": "Accessories",
  "Backpack": "Accessories",
  "Gloves": "Accessories",

  "Sandals": "Footwear",
  "Shoes": "Footwear",
  "Boots": "Footwear",
  "Sneakers": "Footwear",

  "Jacket": "Outerwear"
}

In [ ]:
df.head()

,customer_id,age,gender,item_purchased,category,purchased_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,NaN,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,NaN,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Cloth,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,Not Applicable Size,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,NaN,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df['category']=df['item_purchased'].map(correct_mapping)

In [ ]:
df.groupby('category')['item_purchased'].unique()

category
Accessories                      [Handbag, Sunglasses, Jewelry, Scarf, Hat, Backpack, Belt, Gloves]
Clothing       [Blouse, Sweater, Jeans, Shirt, Shorts, Dress, Skirt, Pants, Hoodie, T-shirt, Socks]
Footwear                                                          [Sandals, Sneakers, Shoes, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: item_purchased, dtype: object

In [ ]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchased_amount          0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

**Treating null values **

In [ ]:
df['size'].unique()

array(['L', 'S', 'Not Applicable Size', 'M', 'Free Size', 'XL'],
      dtype=object)

In [ ]:
df.groupby('Category')['Size'].unique()

Category
Accessory    [M, S, L, XL]
Cloth        [S, L, M, XL]
Footwear     [M, S, XL, L]
Name: Size, dtype: object

In [ ]:
df.groupby('item_purchased')['size'].unique()

item_purchased
Backpack              [XL, M, L, S]
Belt                    [Free Size]
Blouse                [L, M, S, XL]
Boots         [Not Applicable Size]
Coat                  [L, M, S, XL]
Dress                 [M, XL, S, L]
Gloves                [L, S, M, XL]
Handbag                 [Free Size]
Hat                   [S, L, M, XL]
Hoodie                [M, S, L, XL]
Jacket                [M, XL, L, S]
Jeans                 [S, XL, M, L]
Jewelry               [M, L, XL, S]
Pants                 [M, XL, L, S]
Sandals       [Not Applicable Size]
Scarf                   [Free Size]
Shirt                 [M, L, S, XL]
Shoes                 [L, M, S, XL]
Shorts                [L, S, M, XL]
Skirt                 [M, XL, S, L]
Sneakers      [Not Applicable Size]
Socks                 [XL, L, S, M]
Sunglasses              [Free Size]
Sweater               [L, S, M, XL]
T-shirt               [L, M, XL, S]
Name: size, dtype: object

In [ ]:
# Treating null values ot replacing all valies electronic
df.loc[df['category']=='Electronic','Size']='Not Aplicable'

In [ ]:
df.groupby('Category')['Size'].unique()

Category
Accessory    [M, S, L, XL]
Cloth        [S, L, M, XL]
Footwear     [M, S, XL, L]
Name: Size, dtype: object

In [ ]:
# Treating null values or eplacing all values in the Accessory category
df.loc[df['category']=='Accessories','size']='Free Size'

In [ ]:
df.groupby('category')['size'].unique()

category
Accessories                           [Free Size]
Clothing                            [L, S, M, XL]
Footwear       [Not Applicable Size, L, M, S, XL]
Outerwear                           [L, M, S, XL]
Name: size, dtype: object

In [ ]:
df.loc[df['category']=='Footwear','size']='Not Applicable Size'

In [ ]:
df.groupby('category')['size'].unique()

category
Accessories              [Free Size]
Clothing               [L, S, M, XL]
Footwear       [Not Applicable Size]
Outerwear              [L, M, S, XL]
Name: size, dtype: object

**Review Rating**

In [ ]:
df.head(20)

,customer_id,age,gender,item_purchased,category,purchased_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,Not Applicable Size,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,Not Applicable Size,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,Free Size,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly
10,11,53,Male,Shoes,Footwear,34,Arkansas,Not Applicable Size,Purple,Fall,4.1,Yes,Store Pickup,Yes,Yes,26,Bank Transfer,Bi-Weekly
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,Yes,10,Bank Transfer,Fortnightly
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,Yes,37,Venmo,Fortnightly
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,Yes,31,PayPal,Weekly
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,Yes,34,Debit Card,Weekly
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,Yes,8,PayPal,Monthly
16,17,25,Male,Sunglasses,Accessories,36,Alabama,Free Size,Gray,Spring,4.1,Yes,Next Day Air,Yes,Yes,44,Debit Card,Bi-Weekly
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,Yes,36,Venmo,Quarterly
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,Yes,17,Cash,Weekly
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,Yes,46,Debit Card,Bi-Weekly

In [ ]:
# Mean of review rating

In [ ]:
df['Review Rating'].mean()

np.float64(3.750064716541548)

In [ ]:
# Mean of review rating
df['Review Rating'].median()

3.8

In [ ]:
df['Review Rating'].mode()

0    3.4
Name: Review Rating, dtype: float64

In [ ]:
df.groupby('category')['Review Rating'].mean()

Category
Accessory    3.749042
Cloth        3.710980
Footwear     3.808277
Name: Review Rating, dtype: float64

In [ ]:
df.groupby('Item Purchased')['Review Rating'].mean()

Item Purchased
Backpack      3.752448
Belt          3.763522
Blouse        3.680473
Boots         3.818881
Coat          3.727673
Dress         3.750000
Gloves        3.862774
Handbag       3.775163
Hat           3.801307
Hoodie        3.716779
Jacket        3.763190
Jeans         3.648387
Jewelry       3.758824
Pants         3.720833
Sandals       3.844654
Scarf         3.705806
Shirt         3.622024
Shoes         3.749660
Shorts        3.714194
Skirt         3.785350
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.751572
Sweater       3.760870
T-shirt       3.779310
Name: Review Rating, dtype: float64

In [ ]:
df.groupby('Item Purchased')['Review Rating'].transform('mean')

0       3.680473
1       3.760870
2       3.648387
3       3.844654
4       3.680473
5       3.757931
6       3.622024
7       3.714194
8       3.727673
9       3.775163
10      3.749660
11      3.714194
12      3.727673
13      3.750000
14      3.727673
15      3.785350
16      3.751572
17      3.750000
18      3.760870
19      3.720833
20      3.720833
21      3.720833
22      3.720833
23      3.720833
24      3.763190
25      3.716779
26      3.758824
27      3.714194
28      3.775163
29      3.750000
30      3.758824
31      3.750000
32      3.763190
33      3.720833
34      3.779310
35      3.680473
36      3.779310
37      3.648387
38      3.750000
39      3.720833
40      3.775163
41      3.705806
42      3.727673
43      3.705806
44      3.801307
45      3.755063
46      3.622024
47      3.758824
48      3.622024
49      3.716779
50      3.680473
51      3.785350
52      3.779310
53      3.785350
54      3.727673
55      3.763190
56      3.752448
57      3.727673
58      3.716779
59      3.763522
60      3.760870
61      3.705806
62      3.757931
63      3.751572
64      3.818881
65      3.752448
66      3.680473
67      3.727673
68      3.775163
69      3.763522
70      3.763522
71      3.750000
72      3.750000
73      3.720833
74      3.862774
75      3.705806
76      3.801307
77      3.750000
78      3.785350
79      3.763190
80      3.844654
81      3.749660
82      3.720833
83      3.750000
84      3.727673
85      3.751572
86      3.716779
87      3.749660
88      3.779310
89      3.763190
90      3.801307
91      3.705806
92      3.763190
93      3.760870
94      3.785350
95      3.757931
96      3.862774
97      3.749660
98      3.648387
99      3.716779
100     3.751572
101     3.727673
102     3.755063
103     3.818881
104     3.751572
105     3.752448
106     3.763190
107     3.757931
108     3.755063
109     3.779310
110     3.752448
111     3.763522
112     3.862774
113     3.801307
114     3.727673
115     3.785350
116     3.749660
117     3.844654
118     3.760870
119     3.727673
120     3.801307
121     3.714194
122     3.752448
123     3.760870
124     3.760870
125     3.714194
126     3.714194
127     3.760870
128     3.705806
129     3.750000
130     3.705806
131     3.785350
132     3.752448
133     3.760870
134     3.801307
135     3.844654
136     3.680473
137     3.757931
138     3.785350
139     3.727673
140     3.622024
141     3.862774
142     3.763190
143     3.727673
144     3.749660
145     3.758824
146     3.785350
147     3.749660
148     3.862774
149     3.720833
150     3.818881
151     3.751572
152     3.622024
153     3.716779
154     3.750000
155     3.755063
156     3.714194
157     3.801307
158     3.622024
159     3.862774
160     3.862774
161     3.752448
162     3.751572
163     3.785350
164     3.775163
165     3.775163
166     3.757931
167     3.862774
168     3.749660
169     3.763190
170     3.622024
171     3.714194
172     3.758824
173     3.801307
174     3.749660
175     3.727673
176     3.752448
177     3.716779
178     3.785350
179     3.818881
180     3.844654
181     3.720833
182     3.862774
183     3.785350
184     3.757931
185     3.779310
186     3.752448
187     3.749660
188     3.716779
189     3.680473
190     3.727673
191     3.801307
192     3.749660
193     3.763522
194     3.752448
195     3.763190
196     3.818881
197     3.705806
198     3.758824
199     3.801307
200     3.750000
201     3.680473
202     3.801307
203     3.705806
204     3.757931
205     3.622024
206     3.779310
207     3.862774
208     3.785350
209     3.844654
210     3.763190
211     3.785350
212     3.775163
213     3.775163
214     3.763190
215     3.705806
216     3.714194
217     3.751572
218     3.779310
219     3.763522
220     3.757931
221     3.801307
222     3.862774
223     3.720833
224     3.755063
225     3.763190
226     3.749660
227     3.648387
228     3.755063
229     3.844654
230     3.705806
231     3.680473
232     3.758824
233     3.760870
234     3.862774
235     3.751572
236     3.727673
237     3.750000
238     3.785350
239     3.720833
240     3.760870
241     3.716779
242     3.727673
243     3.758824
244     3.763522
245     3.844654
246     3.751572
247     3.760870
248     3.763522
249     3.775163
250     3.785350
251     3.775163
252     3.714194
253     3.818881
254     3.751572
255     3.705806
256     3.758824
257     3.775163
258     3.862774
259     3.648387
260     3.801307
261     3.648387
262     3.720833
263     3.714194
264     3.720833
265     3.752448
266     3.758824
267     3.760870
268     3.749660
269     3.680473
270     3.648387
271     3.751572
272     3.758824
273     3.727673
274     3.758824
275     3.752448
276     3.785350
277     3.622024
278     3.760870
279     3.757931
280     3.844654
281     3.763522
282     3.785350
283     3.760870
284     3.785350
285     3.775163
286     3.758824
287     3.705806
288     3.779310
289     3.727673
290     3.779310
291     3.750000
292     3.749660
293     3.775163
294     3.785350
295     3.751572
296     3.844654
297     3.749660
298     3.779310
299     3.757931
300     3.801307
301     3.785350
302     3.760870
303     3.844654
304     3.750000
305     3.760870
306     3.763190
307     3.862774
308     3.775163
309     3.750000
310     3.720833
311     3.648387
312     3.720833
313     3.750000
314     3.720833
315     3.758824
316     3.775163
317     3.760870
318     3.752448
319     3.714194
320     3.758824
321     3.757931
322     3.763522
323     3.716779
324     3.622024
325     3.720833
326     3.705806
327     3.727673
328     3.727673
329     3.755063
330     3.760870
331     3.622024
332     3.622024
333     3.760870
334     3.680473
335     3.760870
336     3.801307
337     3.760870
338     3.716779
339     3.714194
340     3.714194
341     3.801307
342     3.727673
343     3.844654
344     3.785350
345     3.749660
346     3.648387
347     3.844654
348     3.680473
349     3.801307
350     3.760870
351     3.785350
352     3.648387
353     3.757931
354     3.758824
355     3.758824
356     3.720833
357     3.763522
358     3.801307
359     3.757931
360     3.720833
361     3.779310
362     3.757931
363     3.714194
364     3.749660
365     3.862774
366     3.755063
367     3.750000
368     3.775163
369     3.763522
370     3.705806
371     3.757931
372     3.760870
373     3.727673
374     3.758824
375     3.751572
376     3.749660
377     3.705806
378     3.750000
379     3.779310
380     3.752448
381     3.758824
382     3.648387
383     3.751572
384     3.760870
385     3.714194
386     3.758824
387     3.727673
388     3.775163
389     3.818881
390     3.862774
391     3.760870
392     3.779310
393     3.749660
394     3.705806
395     3.757931
396     3.750000
397     3.763522
398     3.818881
399     3.705806
400     3.818881
401     3.779310
402     3.752448
403     3.757931
404     3.779310
405     3.648387
406     3.862774
407     3.716779
408     3.757931
409     3.714194
410     3.760870
411     3.648387
412     3.763190
413     3.758824
414     3.752448
415     3.727673
416     3.763522
417     3.844654
418     3.760870
419     3.714194
420     3.755063
421     3.622024
422     3.720833
423     3.705806
424     3.760870
425     3.648387
426     3.720833
427     3.752448
428     3.727673
429     3.844654
430     3.622024
431     3.801307
432     3.622024
433     3.785350
434     3.749660
435     3.727673
436     3.720833
437     3.758824
438     3.763522
439     3.763190
440     3.622024
441     3.716779
442     3.751572
443     3.751572
444     3.750000
445     3.818881
446     3.622024
447     3.714194
448     3.862774
449     3.758824
450     3.818881
451     3.758824
452     3.720833
453     3.758824
454     3.763190
455     3.680473
456     3.680473
457     3.862774
458     3.714194
459     3.801307
460     3.749660
461     3.818881
462     3.763190
463     3.758824
464     3.751572
465     3.785350
466     3.648387
467     3.752448
468     3.752448
469     3.714194
470     3.750000
471     3.705806
472     3.648387
473     3.727673
474     3.760870
475     3.757931
476     3.705806
477     3.760870
478     3.758824
479     3.775163
480     3.716779
481     3.801307
482     3.763522
483     3.716779
484     3.801307
485     3.749660
486     3.844654
487     3.763190
488     3.760870
489     3.755063
490     3.757931
491     3.727673
492     3.622024
493     3.752448
494     3.818881
495     3.775163
496     3.750000
497     3.757931
498     3.818881
499     3.749660
500     3.779310
501     3.818881
502     3.720833
503     3.749660
504     3.749660
505     3.779310
506     3.705806
507     3.714194
508     3.758824
509     3.779310
510     3.622024
511     3.622024
512     3.862774
513     3.705806
514     3.785350
515     3.801307
516     3.716779
517     3.818881
518     3.680473
519     3.763522
520     3.751572
521     3.714194
522     3.862774
523     3.844654
524     3.622024
525     3.727673
526     3.720833
527     3.779310
528     3.757931
529     3.714194
530     3.727673
531     3.844654
532     3.720833
533     3.844654
534     3.862774
535     3.779310
536     3.763190
537     3.680473
538     3.755063
539     3.727673
540     3.750000
541     3.763190
542     3.818881
543     3.785350
544     3.844654
545     3.727673
546     3.716779
547     3.763190
548     3.752448
549     3.752448
550     3.763522
551     3.727673
552     3.779310
553     3.751572
554     3.757931
555     3.862774
556     3.727673
557     3.622024
558     3.757931
559     3.705806
560     3.758824
561     3.763190
562     3.648387
563     3.749660
564     3.716779
565     3.752448
566     3.757931
567     3.680473
568     3.720833
569     3.785350
570     3.779310
571     3.763190
572     3.705806
573     3.720833
574     3.757931
575     3.648387
576     3.801307
577     3.785350
578     3.844654
579     3.844654
580     3.760870
581     3.760870
582     3.763190
583     3.714194
584     3.755063
585     3.755063
586     3.716779
587     3.755063
588     3.818881
589     3.622024
590     3.763522
591     3.752448
592     3.818881
593     3.727673
594     3.716779
595     3.749660
596     3.749660
597     3.758824
598     3.750000
599     3.818881
600     3.801307
601     3.752448
602     3.749660
603     3.775163
604     3.751572
605     3.801307
606     3.705806
607     3.716779
608     3.752448
609     3.760870
610     3.714194
611     3.705806
612     3.801307
613     3.727673
614     3.758824
615     3.844654
616     3.862774
617     3.752448
618     3.763190
619     3.752448
620     3.752448
621     3.751572
622     3.755063
623     3.749660
624     3.720833
625     3.758824
626     3.751572
627     3.844654
628     3.760870
629     3.749660
630     3.758824
631     3.818881
632     3.752448
633     3.844654
634     3.757931
635     3.716779
636     3.775163
637     3.760870
638     3.844654
639     3.750000
640     3.785350
641     3.680473
642     3.785350
643     3.760870
644     3.752448
645     3.716779
646     3.818881
647     3.680473
648     3.716779
649     3.720833
650     3.862774
651     3.801307
652     3.751572
653     3.705806
654     3.775163
655     3.775163
656     3.648387
657     3.763190
658     3.752448
659     3.714194
660     3.727673
661     3.622024
662     3.862774
663     3.750000
664     3.720833
665     3.720833
666     3.716779
667     3.751572
668     3.779310
669     3.763190
670     3.760870
671     3.763190
672     3.755063
673     3.622024
674     3.758824
675     3.751572
676     3.720833
677     3.755063
678     3.680473
679     3.844654
680     3.757931
681     3.622024
682     3.763190
683     3.844654
684     3.801307
685     3.680473
686     3.760870
687     3.862774
688     3.705806
689     3.716779
690     3.714194
691     3.752448
692     3.751572
693     3.714194
694     3.750000
695     3.714194
696     3.763522
697     3.705806
698     3.818881
699     3.775163
700     3.720833
701     3.818881
702     3.622024
703     3.750000
704     3.716779
705     3.720833
706     3.648387
707     3.622024
708     3.752448
709     3.763190
710     3.705806
711     3.818881
712     3.680473
713     3.716779
714     3.763190
715     3.648387
716     3.758824
717     3.755063
718     3.622024
719     3.714194
720     3.758824
721     3.680473
722     3.760870
723     3.758824
724     3.779310
725     3.801307
726     3.714194
727     3.760870
728     3.648387
729     3.751572
730     3.818881
731     3.727673
732     3.622024
733     3.750000
734     3.622024
735     3.751572
736     3.750000
737     3.751572
738     3.751572
739     3.714194
740     3.648387
741     3.779310
742     3.720833
743     3.751572
744     3.818881
745     3.779310
746     3.844654
747     3.714194
748     3.801307
749     3.705806
750     3.779310
751     3.862774
752     3.705806
753     3.818881
754     3.862774
755     3.727673
756     3.763522
757     3.716779
758     3.749660
759     3.750000
760     3.862774
761     3.758824
762     3.763522
763     3.760870
764     3.785350
765     3.757931
766     3.862774
767     3.727673
768     3.752448
769     3.755063
770     3.757931
771     3.760870
772     3.648387
773     3.801307
774     3.801307
775     3.775163
776     3.622024
777     3.755063
778     3.755063
779     3.750000
780     3.749660
781     3.705806
782     3.716779
783     3.779310
784     3.648387
785     3.714194
786     3.801307
787     3.775163
788     3.720833
789     3.775163
790     3.760870
791     3.705806
792     3.757931
793     3.720833
794     3.752448
795     3.844654
796     3.755063
797     3.727673
798     3.755063
799     3.763522
800     3.755063
801     3.763522
802     3.720833
803     3.714194
804     3.818881
805     3.750000
806     3.648387
807     3.779310
808     3.749660
809     3.818881
810     3.705806
811     3.757931
812     3.818881
813     3.775163
814     3.622024
815     3.801307
816     3.760870
817     3.775163
818     3.622024
819     3.751572
820     3.757931
821     3.716779
822     3.622024
823     3.751572
824     3.680473
825     3.763522
826     3.750000
827     3.749660
828     3.755063
829     3.755063
830     3.714194
831     3.862774
832     3.763190
833     3.775163
834     3.752448
835     3.818881
836     3.862774
837     3.716779
838     3.727673
839     3.622024
840     3.622024
841     3.760870
842     3.622024
843     3.716779
844     3.844654
845     3.763522
846     3.818881
847     3.716779
848     3.844654
849     3.648387
850     3.749660
851     3.844654
852     3.750000
853     3.801307
854     3.720833
855     3.755063
856     3.622024
857     3.714194
858     3.763190
859     3.716779
860     3.749660
861     3.785350
862     3.727673
863     3.757931
864     3.648387
865     3.680473
866     3.751572
867     3.763190
868     3.750000
869     3.801307
870     3.716779
871     3.775163
872     3.648387
873     3.818881
874     3.763190
875     3.844654
876     3.763522
877     3.775163
878     3.751572
879     3.785350
880     3.752448
881     3.844654
882     3.818881
883     3.757931
884     3.785350
885     3.750000
886     3.714194
887     3.775163
888     3.705806
889     3.763522
890     3.862774
891     3.785350
892     3.714194
893     3.752448
894     3.716779
895     3.801307
896     3.758824
897     3.622024
898     3.763522
899     3.760870
900     3.801307
901     3.705806
902     3.801307
903     3.763190
904     3.779310
905     3.750000
906     3.720833
907     3.760870
908     3.751572
909     3.763522
910     3.716779
911     3.720833
912     3.716779
913     3.757931
914     3.750000
915     3.750000
916     3.648387
917     3.760870
918     3.714194
919     3.622024
920     3.763522
921     3.727673
922     3.757931
923     3.622024
924     3.755063
925     3.648387
926     3.648387
927     3.757931
928     3.750000
929     3.818881
930     3.779310
931     3.727673
932     3.785350
933     3.757931
934     3.648387
935     3.716779
936     3.749660
937     3.714194
938     3.680473
939     3.779310
940     3.763522
941     3.775163
942     3.750000
943     3.801307
944     3.763522
945     3.818881
946     3.727673
947     3.680473
948     3.801307
949     3.648387
950     3.752448
951     3.750000
952     3.801307
953     3.751572
954     3.801307
955     3.750000
956     3.622024
957     3.705806
958     3.757931
959     3.785350
960     3.758824
961     3.818881
962     3.751572
963     3.818881
964     3.844654
965     3.818881
966     3.750000
967     3.716779
968     3.714194
969     3.727673
970     3.648387
971     3.751572
972     3.757931
973     3.763190
974     3.785350
975     3.760870
976     3.779310
977     3.763522
978     3.862774
979     3.801307
980     3.818881
981     3.763522
982     3.727673
983     3.801307
984     3.749660
985     3.775163
986     3.705806
987     3.775163
988     3.720833
989     3.749660
990     3.751572
991     3.714194
992     3.763190
993     3.844654
994     3.749660
995     3.758824
996     3.844654
997     3.720833
998     3.749660
999     3.755063
1000    3.755063
1001    3.750000
1002    3.749660
1003    3.801307
1004    3.752448
1005    3.752448
1006    3.720833
1007    3.862774
1008    3.705806
1009    3.716779
1010    3.648387
1011    3.752448
1012    3.844654
1013    3.763522
1014    3.749660
1015    3.862774
1016    3.763522
1017    3.763190
1018    3.750000
1019    3.622024
1020    3.705806
1021    3.727673
1022    3.775163
1023    3.751572
1024    3.779310
1025    3.622024
1026    3.775163
1027    3.758824
1028    3.716779
1029    3.862774
1030    3.727673
1031    3.844654
1032    3.818881
1033    3.720833
1034    3.755063
1035    3.680473
1036    3.775163
1037    3.758824
1038    3.720833
1039    3.763522
1040    3.648387
1041    3.622024
1042    3.763522
1043    3.648387
1044    3.648387
1045    3.760870
1046    3.757931
1047    3.755063
1048    3.755063
1049    3.751572
1050    3.757931
1051    3.755063
1052    3.749660
1053    3.680473
1054    3.714194
1055    3.763190
1056    3.760870
1057    3.763190
1058    3.705806
1059    3.763190
1060    3.760870
1061    3.727673
1062    3.818881
1063    3.716779
1064    3.801307
1065    3.779310
1066    3.727673
1067    3.750000
1068    3.622024
1069    3.785350
1070    3.758824
1071    3.801307
1072    3.714194
1073    3.705806
1074    3.758824
1075    3.751572
1076    3.727673
1077    3.763190
1078    3.760870
1079    3.727673
1080    3.705806
1081    3.763522
1082    3.801307
1083    3.752448
1084    3.779310
1085    3.758824
1086    3.751572
1087    3.648387
1088    3.720833
1089    3.752448
1090    3.705806
1091    3.760870
1092    3.758824
1093    3.757931
1094    3.758824
1095    3.727673
1096    3.727673
1097    3.751572
1098    3.775163
1099    3.760870
1100    3.720833
1101    3.862774
1102    3.760870
1103    3.716779
1104    3.801307
1105    3.779310
1106    3.785350
1107    3.757931
1108    3.714194
1109    3.716779
1110    3.716779
1111    3.749660
1112    3.716779
1113    3.751572
1114    3.785350
1115    3.801307
1116    3.752448
1117    3.751572
1118    3.763522
1119    3.758824
1120    3.757931
1121    3.779310
1122    3.775163
1123    3.801307
1124    3.760870
1125    3.844654
1126    3.705806
1127    3.622024
1128    3.862774
1129    3.716779
1130    3.758824
1131    3.622024
1132    3.716779
1133    3.749660
1134    3.779310
1135    3.785350
1136    3.775163
1137    3.622024
1138    3.720833
1139    3.727673
1140    3.648387
1141    3.862774
1142    3.779310
1143    3.818881
1144    3.648387
1145    3.757931
1146    3.757931
1147    3.801307
1148    3.720833
1149    3.758824
1150    3.758824
1151    3.680473
1152    3.775163
1153    3.622024
1154    3.750000
1155    3.779310
1156    3.749660
1157    3.763522
1158    3.763522
1159    3.775163
1160    3.705806
1161    3.714194
1162    3.844654
1163    3.720833
1164    3.750000
1165    3.779310
1166    3.750000
1167    3.755063
1168    3.705806
1169    3.752448
1170    3.785350
1171    3.755063
1172    3.727673
1173    3.758824
1174    3.752448
1175    3.763522

In [ ]:
df.head()

,customer_id,age,gender,item_purchased,category,purchased_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,Not Applicable Size,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

**Previous Purchase**

In [ ]:
df['previous_purchases']= df['previous_purchases'].fillna

In [ ]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchased_amount          0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [ ]:
df['Purchase Amount (USD)']= df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

In [ ]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                  2221
Purchase Amount (USD)        0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating               37
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
dtype: int64

In [ ]:
df['Review Rating']= df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [ ]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                  2221
Purchase Amount (USD)        0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Shipping Type                0
Discount Applied             0
Promo Code Used              0
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
dtype: int64

**Checking Duplicates**

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (USD), Location, Size, Color, Season, Review Rating, Subscription Status, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Payment Method, Frequency of Purchases]
Index: []

In [ ]:
df.count()

customer_id               3900
age                       3900
gender                    3900
item_purchased            3900
category                  3900
purchased_amount          3900
location                  3900
size                      3900
color                     3900
season                    3900
review_rating             3900
subscription_status       3900
shipping_type             3900
discount_applied          3900
promo_code_used           3900
previous_purchases        3900
payment_method            3900
frequency_of_purchases    3900
dtype: int64

In [ ]:
df.head()

   customer_id  age gender item_purchased  category  purchased_amount  \
0            1   55   Male         Blouse  Clothing                53
1            2   19   Male        Sweater  Clothing                64
2            3   50   Male          Jeans  Clothing                73
3            4   21   Male        Sandals  Footwear                90
4            5   45   Male         Blouse  Clothing                49

        location                 size      color  season  review_rating  \
0       Kentucky                    L       Gray  Winter            3.1
1          Maine                    L     Maroon  Winter            3.1
2  Massachusetts                    S     Maroon  Spring            3.1
3   Rhode Island  Not Applicable Size     Maroon  Spring            3.5
4         Oregon                    M  Turquoise  Spring            2.7

  subscription_status  shipping_type discount_applied promo_code_used  \
0                 Yes        Express              Yes             Yes
1                 Yes        Express              Yes             Yes
2                 Yes  Free Shipping              Yes             Yes
3                 Yes   Next Day Air              Yes             Yes
4                 Yes  Free Shipping              Yes             Yes


**Renaming the headers**

In [ ]:

df.columns = [
    'customer_id', 'age', 'gender', 'item_purchased', 'category',
    'purchase_amount_usd', 'location', 'size', 'color', 'season',
    'review_rating', 'subscription_status', 'shipping_type', 'discount_applied',
    'promo_code_used', 'previous_purchases', 'payment_method',
    'frequency_of_purchases'
]

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
df=df.rename(columns={"purchase_amount_usd":"purchased_amount"})

In [ ]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchased_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
df.head(20)

    customer_id  age gender item_purchased     category  purchased_amount  \
0             1   55   Male         Blouse     Clothing                53
1             2   19   Male        Sweater     Clothing                64
2             3   50   Male          Jeans     Clothing                73
3             4   21   Male        Sandals     Footwear                90
4             5   45   Male         Blouse     Clothing                49
5             6   46   Male       Sneakers     Footwear                20
6             7   63   Male          Shirt     Clothing                85
7             8   27   Male         Shorts     Clothing                34
8             9   26   Male           Coat    Outerwear                97
9            10   57   Male        Handbag  Accessories                31
10           11   53   Male          Shoes     Footwear                34
11           12   30   Male         Shorts     Clothing                68
12           13   61   Male           Coat    Outerwear                72
13           14   65   Male          Dress     Clothing                51
14           15   64   Male           Coat    Outerwear                53
15           16   64   Male          Skirt     Clothing                81
16           17   25   Male     Sunglasses  Accessories                36
17           18   53   Male          Dress     Clothing                38
18           19   52   Male        Sweater     Clothing                48
19           20   66   Male          Pants     Clothing                90

         location                 size      color  season  review_rating  \
0        Kentucky                    L       Gray  Winter            3.1
1           Maine                    L     Maroon  Winter            3.1
2   Massachusetts                    S     Maroon  Spring            3.1
3    Rhode Island  Not Applicable Size     Maroon  Spring            3.5
4          Oregon                    M  Turquoise  Spring            2.7
5         Wyoming  Not Applicable Size      White  Summer            2.9
6         Montana                    M       Gray    Fall            3.2
7       Louisiana                    L   Charcoal  Winter            3.2
8   West Virginia                    L     Silver  Summer            2.6
9        Missouri            Free Size       Pink  Spring            4.8
10       Arkansas  Not Applicable Size     Purple    Fall            4.1
11         Hawaii                    S      Olive  Winter            4.9
12       Delaware                    M       Gold  Winter            4.5
13  New Hampshire                    M     Violet  Spring            4.7
14       New York                    L       Teal  Winter            4.7
15   Rhode Island                    M       Teal  Winter            2.8
16        Alabama            Free Size       Gray  Spring            4.1
17    Mississippi                   XL   Lavender  Winter            4.7
18        Montana                    S      Black  Summer            4.6
19   Rhode Island                    M      Green  Summer            3.3

   subscription_status   shipping_type discount_applied promo_code_used  \
0                  Yes         Express              Yes             Yes
1                  Yes         Express              Yes             Yes
2                  Yes   Free Shipping              Yes             Yes
3                  Yes    Next Day Air              Yes             Yes
4                  Yes   Free Shipping              Yes             Yes
5                  Yes        Standard              Yes             Yes
6                  Yes   Free Shipping              Yes             Yes
7                  Yes   Free Shipping              Yes             Yes
8                  Yes         Express              Yes             Yes
9                  Yes  2-Day Shipping              Yes             Yes
10                 Yes    Store Pickup              Yes             Yes
11                 Yes    Store Pickup              Yes             Yes
12                 Yes         Express              Yes             Yes
13                 Yes         Express              Yes             Yes
14                 Yes   Free Shipping              Yes             Yes
15                 Yes    Store Pickup              Yes             Yes
16                 Yes    Next Day Air              Yes             Yes
17                 Yes  2-Day Shipping              Yes             Yes
18                 Yes   Free Shipping              Yes             Yes
19                 Yes        Standard              Yes             Yes


**Connecting to SQL Server**

In [ ]:
# Save your final DataFrame as CSV in Colab
df.to_csv('customer_behavior_analysis.csv', index=False)
print("✅ CSV file created!")

✅ CSV file created!

In [ ]:
from google.colab import files

# This will download the file to your PC
files.download('customer_behavior_analysis.csv')
print("✅ File downloaded to your PC!")

✅ File downloaded to your PC!